{
  homebrew = {
    taps = [
      # "abhinav/tap"
      # "anthropics/tap"
      # "aws/tap"
      # "bridgecrewio/tap"
      "buildkite/buildkite"
      "charmbracelet/tap"
      # "dagger/tap"
      # "keith/formulae"
      "localstack/tap"
      # "minamijoyo/hcledit"
      # "minamijoyo/tfmigrate"
      "minamijoyo/tfschema"
      # "minamijoyo/tfupdate"
      "pulumi/tap"
      "tsonglew/dutis"
      "withgraphite/tap"
      # "wedow/tools"
    ];
    brews = [
      {
        name = "postgresql@16";
        link = true;
      }
      # "anthropics/tap/ant"
      # "abhinav/tap/restack"
      "aspell"
      "docker-credential-helper-ecr"
      # "aws/tap/eksctl"
      # "bridgecrewio/tap/yor"
      "buildkite/buildkite/bk@3"
      "caddy"
      "charmbracelet/tap/freeze"
      "charmbracelet/tap/sequin"
      "cmake"
      # "colima" # TODO: use https://github.com/nix-community/home-manager/blob/master/modules/services/colima.nix ?
      "curl"
      # "ddcctl"
      "direnv"
      # "drewdeponte/oss/git-ps-rs"
      "duti"
      # "felixkratz/formulae/sketchybar"
      "gcc"
      "gh"
      "gnu-getopt"
      # "grafana"
      # "hcledit"
      # "incus"
      # "inframap"
      # "jq"
      # "just"
      # "keith/formulae/zap"
      "kubernetes-cli"
      "lazyjournal"
      "ldcli"
      "libgccjit"
      "libtool"
      "libvterm"
      "llama.cpp"
      "localstack/tap/localstack-cli"
      "luarocks"
      # "mas"
      # "minamijoyo/hcledit/hcledit"
      # "minamijoyo/tfmigrate/tfmigrate"
      "minamijoyo/tfschema/tfschema"
      # "minamijoyo/tfupdate/tfupdate"
      "mkcert"
      "nss"
      "ollama"
      # "pngpaste"
      # "pomdtr/tap/sunbeam"
      # "pulumi/tap/esc"
      # "pulumi/tap/pulumi"
      "redis"
      # "ripgrep"
      # "temporal"
      # "terminal-notifier"
      # "terragrunt"
      "tfenv"
      # "tofuutils/tap/tofuenv"
      "tsonglew/dutis/dutis"
      # "dagger/tap/dagger"
      # "drewdeponte/oss/alt"
      # "podlet"
      # "podman"
      # "podman-tui"
      # "jbangdev/tap/jbang"
      # "wedow/tools/ticket"
      "withgraphite/tap/graphite"
    ];
    casks = [
      "1password-cli"
      "discord"
      "ghostty"
      "hammerspoon"
      "jordanbaird-ice"
      "nikitabobko/tap/aerospace"
      "orbstack"
      "pearcleaner"
      "sf-symbols"
      "tailscale-app"
      "temurin@17"
      "vlc"
      # "inkscape"
      # "obs"
      # "visualvm"
      # "1password" # currently installed manually
      # "dbeaver-community"
      # "gimp"
      # "karabiner-elements"
      # "keybase"
    ];
  };
}
