#!/bin/zsh
#
# This lets you quickly jump into a project directory.
#
# Type:
#
#   c <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_c`. Typically I'm using it like:
#
#    c holm<tab>/bo<tab>
#
# ...to quickly jump into holman/boom, for example.
#
# This also accounts for how Go structures its projects. For example, it will
# autocomplete both on $PROJECTS, and also assume you want to autocomplete on
# your Go projects in $GOPATH/src.


# if project not specified, prompt for it (in a fuzzy fashion)
if [ "$#" -eq "0" ] || [ ! -d "$PROJECTS/$1" ]; then
  preview_cmd="git --git-dir=$PROJECTS/{}/.git status 2>/dev/null || tree --dirsfirst -FL 1"
  choice=$(ls -c --color=never "$PROJECTS" | fzf-tmux --query="$1" --preview "$preview_cmd")
else
  choice="$1"
fi


if [ -d "$PROJECTS/$choice" ]; then

  cd "$PROJECTS/$choice"

  if [ -n "$TMUX_RENAME_WINDOW" ]; then
    tmux rename-window "$choice"
  fi

  # [python]
  # if no venv is activated and there's a pyenv version with matching
  # name, activate it automatically
  if [ -z "$VIRTUAL_ENV" ] && [ -d "$HOME/.pyenv/versions/$choice" ]; then
    pyenv activate "$choice"
  fi

else

  cd "$PROJECTS"

fi


