repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-yaml
  - id: detect-private-key
  - id: detect-aws-credentials
  - id: check-executables-have-shebangs
  - id: file-contents-sorter
    files: 'tool-versions'

- repo: local
  hooks:
    - id: shellcheck
      name: shellcheck
      language: system
      entry: shellcheck
      types_or: [sh, bash, dash, ksh, csh]

    - id: shfmt
      name: shfmt
      minimum_pre_commit_version: 2.4.0
      language: golang
      additional_dependencies: [mvdan.cc/sh/v3/cmd/shfmt@v3.2.2]
      entry: shfmt
      args: [-w]
      types: [shell]
      exclude: zsh/configs-post/completion.zsh

    - id: shellharden
      name: shellharden
      language: system
      entry: shellharden
      types: [shell]
