keys:
  - &user_logan age15xagf0337s3w73sps8dfpnup39rglkul8km9hkc8m9daz5yldu4qqr4yfl
  - &host_nijusan age1kztz3tmrz2tc7sn4y85qrrrypldfdkgxr2e52ra5cjv3dyrrl4ss7aryhk
  - &host_logamma age19cmwczamj0kfney79z0gdytmtgxzytttaacrvq4n0luzn6cnv5dsgfkl0c
  - &machine_nijusan age1fu0d0anhxyrq4eh9sjetq3d4ul8as92svfg3skck02hxruh4dcnqkazd9h  # /etc/ssh/ssh_host_ed25519_key
creation_rules:
  - path_regex: secrets/([^/]+\.(yaml|json|env|ini|bin)|env)$
    key_groups:
      - age:
          - *user_logan
          - *host_nijusan
          - *host_logamma
