keys:
  - &llinn-pgp 32A48B412F1CA30ADB1B54382C3CDAE023DB6616
  - &llinn-ssh age15xagf0337s3w73sps8dfpnup39rglkul8km9hkc8m9daz5yldu4qqr4yfl
  - &nijusan age1nrxg0qkcqfx5s76x3md2jakwd9tslqry0y2k0lp4u4ngjje4z3dq8v3xyq

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *llinn-pgp
      - age:
        - *llinn-ssh
        - *nijusan
