#!/usr/bin/env zsh

antigen use oh-my-zsh

# https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins
antigen bundles <<EOBUNDLES
    asdf
    aws
    cargo
    clvv/fasd
    colored-man-pages
    command-not-found
    docker
    doctl
    emacs
    extract
    fasd
    fzf
    genpass
    git
    github
    gitignore
    gpg-agent
    gradle
    man
    kubectl
    lein
    loganlinn/zzz.plugin.zsh
    mchav/with
    pierpo/fzf-docker
    pip
    safe-paste
    sirhc/okta.plugin.zsh
    sirhc/op.plugin.zsh
    ssh-agent
    terraform
    urltools
    vi-mode
    web-search
    wfxr/forgit
    zsh-interactive-cd
    zsh-users/zaw
    zsh-users/zsh-autosuggestions 
    zsh-users/zsh-completions 
    zsh-users/zsh-history-substring-search 
    zsh-users/zsh-syntax-highlighting
    zsh_reload
EOBUNDLES

[[ -d ~/.jenv ]]  && antigen bundle jenv
[[ -d ~/.pyenv ]] && antigen bundle pyenv
[[ -d ~/.rbenv ]] && antigen bundle rbenv

for bundle in ${ZSH_CUSTOM?}/plugins/*(/)
do
  antigen bundle "${bundle}" --no-local-clone
done

antigen theme "${ANTIGEN_THEME:-romkatv/powerlevel10k}"

antigen apply

###############################################################################

# zsh-users/zsh-autosuggestions
export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
export ZSH_AUTOSUGGEST_USE_ASYNC=1

# wfxr/forgit
export FORGIT_FZF_DEFAULT_OPTS='--preview-window=right:80%'
export FORGIT_ADD_FZF_OPTS='--ansi'

