#!/usr/bin/env zsh

antigen use oh-my-zsh

# See also:
# - https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins
# - https://github.com/unixorn/awesome-zsh-plugins
antigen bundles <<EOL
    colored-man-pages
    fasd
    fzf
    genpass
    git
    gitignore
    gpg-agent
    ssh-agent
    terraform
    urltools
    web-search
    zsh-interactive-cd
    Aloxaf/fzf-tab
    clvv/fasd
    jeffreytse/zsh-vi-mode
    johanhaleby/kubetail
    loganlinn/zzz.plugin.zsh
    wfxr/forgit
    zsh-users/zsh-autosuggestions 
    zsh-users/zsh-completions 
    zsh-users/zsh-history-substring-search 
EOL

[[ -d ~/.pyenv ]] && antigen bundle pyenv
[[ -d ~/.jenv  ]] && antigen bundle jenv

for _zsh_custom_plugin in $ZSH_CUSTOM/plugins/*(/); do
  antigen bundle "$_zsh_custom_plugin" --no-local-clone
done
unset _zsh_custom_plugin

###############################################################################

# zsh-users/zsh-autosuggestions
export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
export ZSH_AUTOSUGGEST_USE_ASYNC=1

# wfxr/forgit
export FORGIT_FZF_DEFAULT_OPTS='--preview-window=right:80%'
export FORGIT_ADD_FZF_OPTS='--ansi'

# jeffreytse/zsh-vi-mode
ZVM_LAZY_KEYBINDINGS=false
ZVM_LINE_INIT_MODE=${ZVM_MODE_INSERT-i}

function zvm_after_init() {
	# zvm overwrites fzf-history-widget bindkey
	if [[ -f $XDG_CONFIG_HOME/fzf/fzf.zsh ]]; then
		. "$XDG_CONFIG_HOME"/fzf/fzf.zsh
	elif [[ -f ~/fzf.zsh ]]; then
		. ~/fzf.zsh
	fi

 [[ -f $ZSH_CUSTOM/plugins/fzf-fasd/fzf-fasd.plugin.zsh ]] &&
   . $ZSH_CUSTOM/plugins/fzf-fasd/fzf-fasd.plugin.zsh
}

###############################################################################

antigen apply
