#!/usr/bin/env zsh

antigen use oh-my-zsh

# https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins
antigen bundles <<EOBUNDLES
    Aloxaf/fzf-tab
    clvv/fasd
    colored-man-pages
    fasd
    fzf
    genpass
    git
    gitignore
    gpg-agent
    jeffreytse/zsh-vi-mode
    johanhaleby/kubetail
    loganlinn/zzz.plugin.zsh
    pyenv
    sirhc/op.plugin.zsh
    ssh-agent
    terraform
    urltools
    web-search
    wfxr/forgit
    zsh-interactive-cd
    zsh-users/zsh-autosuggestions 
    zsh-users/zsh-completions 
    zsh-users/zsh-history-substring-search 
EOBUNDLES

[[ -d ~/.jenv ]] && antigen bundle jenv

antigen bundle --no-local-clone "$ZSH_CUSTOM"/plugins/*(/)

# antigen theme "${ANTIGEN_THEME:-romkatv/powerlevel10k}"

###############################################################################

# zsh-users/zsh-autosuggestions
export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
export ZSH_AUTOSUGGEST_USE_ASYNC=1

# wfxr/forgit
export FORGIT_FZF_DEFAULT_OPTS='--preview-window=right:80%'
export FORGIT_ADD_FZF_OPTS='--ansi'

# jeffreytse/zsh-vi-mode
function zvm_config() {
	ZVM_LINE_INIT_MODE=${ZVM_MODE_INSERT-i}
	ZVM_VI_INSERT_ESCAPE_BINDKEY=fd
}
function zvm_after_init() {
	# zvm overwrites fzf-history-widget bindkey
	if [[ -f $XDG_CONFIG_HOME/fzf/fzf.zsh ]]; then
		. "$XDG_CONFIG_HOME"/fzf/fzf.zsh
	elif [[ -f ~/fzf.zsh ]]; then
		. ~/fzf.zsh
	fi
}

###############################################################################

antigen apply
