[shell_alias]
switch = "mise switch"

[tasks.link]
run = [
  'sudo lns "{{config_root}}/flake.nix" "/etc/nix-darwin/flake.nix"',
  'lns "{{config_root}}/flake.nix" "${XDG_CONFIG_HOME:-$HOME/.config}/home-manager/flake.nix"',
]
quiet = true

[tasks.switch]
description = "Switch the nix-darwin configuration (use --no-cachix to skip Cachix)"
raw_args = true
quiet = true
interactive = true
shell = "bash -o errexit -o pipefail -c"
run = '''
switch() {
  flake="${NIX_DARWIN_FLAKE:-{{config_root}}}"
  args=()
  use_cachix=true

  for arg in "$@"; do
    if [[ "$arg" == "--no-cachix" ]]; then
      use_cachix=false
    else
      args+=("$arg")
    fi
  done

  command=(
    sudo -H command nix run nix-darwin -- switch --flake "$flake" "${args[@]}"
  )

  set -x
  if [[ "$use_cachix" == true ]]; then
    {{config_root}}/bin/cachix-run "${command[@]}"
  else
    "${command[@]}"
  fi
}

switch
'''

[tasks."darwin:rebuild"]
raw = true
run = '''
nix run --inputs-from {{config_root}} nix-darwin --
'''

[tasks."nix:restart"]
description = "Restart nix daemon (supports both Determinate and NixOS daemons)"
quiet = true
run = '''
svcs=$(sudo launchctl list | grep -o 'systems\.determinate\.nix-daemon\|org\.nixos\.nix-daemon')
if [[ -z "$svcs" ]]; then
  echo >&2 "No nix daemon service found"
  exit 1
fi
for svc in $svcs; do
  echo -e "\033[1;32m[restart]\033[0m $svc"
  sudo launchctl kickstart -k "system/$svc"
done
'''

[tasks."kitty-nightly:install"]
raw_args = true
run = '''
curl -L https://sw.kovidgoyal.net/kitty/installer.sh |
    sh /dev/stdin \
      installer=nightly \
      dest="$HOME/Applications/kitty-nightly" \
      launch=n \
      "$@"
'''

[tasks."kitty-nightly:run"]
alias = 'kitty-nightly'
raw_args = true
run = '''
env -u KITTY_DEVELOP_FROM -u KITTY_INSTALLATION_DIR \
    "$HOME/Applications/kitty-nightly/kitty.app/Contents/MacOS/kitty" \
    "$@"
'''
