#!/usr/bin/env bash

set -eo pipefail

forgeUrl="https://github.com"
emacsRepoUrl="${forgeUrl}/doomemacs/doomemacs"
doomRepoUrl="${forgeUrl}/loganlinn/.doom.d"
emacsDir=$HOME/.emacs.d
doomDir=$HOME/.doom.d

if ! [[ -d ${emacsDir}/.git ]]; then
  git clone --depth=1 --single-branch "${emacsRepoUrl}" "${emacsDir}"
fi

if ! [[ -d ${doomDir} ]]; then
  git clone "${doomRepoUrl}" "${doomDir}"
fi
