#!/usr/bin/env bash

set -e

BOLD="\e[1m"
RESET="\e[0m"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

nix_repl_command=(nix repl --file "$HERE/repl.nix")

if [[ $# -eq 0 ]]; then
  if [[ $NIX_DARWIN_FLAKE == *"#"* ]]; then
    nix_repl_command+=(--argstr name "${NIX_DARWIN_FLAKE#*'#'}")
  else
    nix_repl_command+=(--argstr name "$(scutil --get LocalHostName)")
  fi
fi

echo -e "${BOLD}${nix_repl_command[*]}${RESET}" >&2
exec "${nix_repl_command[@]}"
