###############################################################################
# starship.toml - shell prompt configuration
#
# For reference: starship print-config
#      See also: https://starship.rs/config
###############################################################################

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$nix_shell\
$python\
$cmd_duration\
$line_break\
$jobs\
$battery\
$shlvl\
$shell\
$character"""

[character]
success_symbol = "[❯](bold green)"
error_symbol   = "[❯](bold red)"
vicmd_symbol   = "[❮](bold yellow)"

[git_branch]
format = "[$branch]($style) "
style = "dimmed"

[git_status]
style = "dimmed"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = " [$duration]($style)"
style = "yellow"
