export PATH="$HOME/bin:$PATH"
export PATH="$ZSH/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.rbenv/shims:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="/snap/bin:$PATH"

export MANPATH="/usr/local/man:$MANPATH"
export MANPATH="/usr/local/mysql/man:$MANPATH"
export MANPATH="/usr/local/git/man:$MANPATH"
