#!/usr/bin/env bash

set -e

BOLD="\e[1m"
RESET="\e[0m"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

nix_repl_command=(
  nix repl
  --file "$HERE/repl.nix"
  --argstr hostname "$(hostname -s)"
)

echo -e "${BOLD}${nix_repl_command[*]}${RESET}" >&2

exec "${nix_repl_command[@]}"
