{
  config,
  lib,
  ...
}:
with lib;
let
  cfg = config.programs.borders;
  flakeDir = config.my.flakeDirectory;
in
{
  options.programs.borders = {
    enable = mkEnableOption "jankyborders window border";

    activeColor = mkOption {
      type = types.str;
      default = "0xffbd93f9";
      description = "Border color for focused window (0xAARRGGBB format)";
    };

    inactiveColor = mkOption {
      type = types.str;
      default = "0xff414550";
      description = "Border color for unfocused windows (0xAARRGGBB format)";
    };

    defaultProfile = mkOption {
      type = types.str;
      default = "default";
      description = "Profile to run when bordersrc is invoked";
    };

    profiles = mkOption {
      type = types.attrsOf types.path;
      default = {
        default = "${flakeDir}/config/borders/default.sh";
      };
      description = "Map of profile names to out-of-store script paths";
    };
  };

  config = mkIf cfg.enable {
    home-manager.users.${config.my.user.name} = {config, ...}: {
      xdg.configFile = {
        # Main entry point - nix-generated with colors
        "borders/bordersrc" = {
          executable = true;
          text = ''
            #!/bin/bash
            # Generated by nix - runs default profile with nix-configured colors
            #
            # Colors (from nix):
            #   active_color=${cfg.activeColor}
            #   inactive_color=${cfg.inactiveColor}
            #
            # Profile: ${cfg.defaultProfile}

            ~/.config/borders/${cfg.defaultProfile}.sh \
              active_color=${cfg.activeColor} \
              inactive_color=${cfg.inactiveColor}
          '';
        };
      } // mapAttrs' (name: path: {
        name = "borders/${name}.sh";
        value = {
          source = config.lib.file.mkOutOfStoreSymlink path;
        };
      }) cfg.profiles;
    };
  };
}
