#!/usr/bin/env bash

BABASHKA_INSTALLER_URL=https://raw.githubusercontent.com/babashka/babashka/master/install

echo "Fetching latest version of the script..." >&2
echo "GET $BABASHKA_INSTALLER_URL" >&2

exec curl -sSLf "$BABASHKA_INSTALLER_URL" | bash -s -- "$@"
