#!/usr/bin/env bash

set -e

: "${DOWNLOAD_URL=https://storage.googleapis.com/container-diff/latest/container-diff-linux-amd64}"
: "${DOWNLOAD_DIR=${TMPDIR-/tmp}}"
: "${INSTALL_DIR=$HOME/.local/bin}"

tmpbin=$(mktemp --tmpdir="$DOWNLOAD_DIR" "${DOWNLOAD_URL##*/}".XXX)
trap 'rm -f "$tmpbin"' EXIT
echo "Downloading $DOWNLOAD_URL" >&2
curl -Lo "$tmpbin" "$DOWNLOAD_URL"
chmod +x "$tmpbin"
mkdir -p "$INSTALL_DIR"
install "$tmpbin" "$INSTALL_DIR"/container-diff
echo "Installed $INSTALL_DIR" >&2
"$INSTALL_DIR"/container-diff version

