#!/usr/bin/env bash

set -e

themesdir="${XDG_DATA_HOME:-$HOME/.local/share}/themes"
gh release download \
  -R EliverLara/Nordic \
  --pattern "Nordic-*.tar.xz" \
  -D "$themesdir"

unxz "$themesdir/*.xz"
