#!/usr/bin/env bash
#
# https://sw.kovidgoyal.net/kitty/binary/
#
set -e
set -o pipefail
set -x

curl -Lf https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin dest="$HOME/.local" launch=n
[[ -d ~/.local/kitty.app ]] || exit 1
ln -sbf ~/.local/kitty.app/bin/kitty ~/.local/bin/
cp -b ~/.local/kitty.app/share/applications/kitty.desktop ~/.local/share/applications/
sed -i "s|Icon=kitty|Icon=/home/$USER/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g" ~/.local/share/applications/kitty.desktop
