#!/usr/bin/env bash

set -e

prefix=${POLY_PREFIX:-$HOME/.local}

tag_name=$(curl -sL https://api.github.com/repos/polyfy/polylith/releases/latest | jq -r .tag_name)

target="$prefix/share/polylith/$tag_name"

mkdir -p "$target"

curl -sLo "$target"/poly.jar "https://github.com/polyfy/polylith/releases/download/${tag_name}/poly-${tag_name#v*}.jar"

cat <<EOF >"$target"/poly
#!/bin/sh
java="\${JAVA_HOME:+"\$JAVA_HOME"/bin/}java"
exec "\$java" -jar "$target"/poly.jar "\$@"
EOF

chmod +x "$target"/poly

mkdir -p "$prefix"/bin

ln -sf "$target"/poly "$prefix"/bin/poly

