#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -eu

source "$(dirname "$0")/common.sh"
cd "$DOTFILES"

for installer in */install.sh; do
  if [[ -x "$installer" ]]; then
    info "installing $(basename "$(dirname "$installer")")"
    sh -c "$installer" || fail "errored $(realpath "$installer")"
    success "ran $(realpath "$installer")"
  else
    warning "skipped $installer (reason: not executable)"
  fi
done
