#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -eu

source "$(dirname "$0")/common.sh"
cd "$DOTFILES"

for installer in $(find . -name install.sh); do
    if [[ -x "$installer" ]]; then
        info "running $installer"        
        sh -c "${installer}"
    else
        warning "$installer is not executable"
    fi
done