#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -eu

source "$(dirname "$0")/common.sh"
cd "$DOTFILES_ROOT"

exec_installers() {
    while read installer; do
        info "running $installer"
        sh -c "${installer}"
    done
}

# find the installers and run them iteratively
find . -name install.sh | exec_installers
find . -name "install.$PLATFORM.sh" | exec_installers