[options]
auto_disable_touchpad = 1
automatic_update = false
buffer_index_type = 4
colorscheme = "nord"
colorscheme_bg = "dark"
enable_guicolors = true
enable_neomake = true
enable_statusline_mode = false
enable_tabline_filetype_icon = true
enable_vimfiler_gitstatus = true
# filemanager = "defx"
filetree_direction = "left"
guifont = "JetBrainsMono Nerd Font Mono:h11"
statusline_iseparator = "bar"
statusline_separator = "arrow"
statusline_unicode_symbols = true
vimcompatible = true
windows_index_type = 3

[[custom_plugins]]
repo = "arcticicestudio/nord-vim"
merged = false

[[custom_plugins]]
repo = "vito-c/jq.vim"
merged = false

[[custom_plugins]]
repo = "guns/vim-sexp"
merged = false

[[custom_plugins]]
repo = "tpope/vim-sexp-mappings-for-regular-people"
merged = false

[[custom_plugins]]
repo = "Olical/conjure"
merged = false

[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = "checkers"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "tmux"

[[layers]]
name = "fzf"

[[layers]]
name = "git"

[[layers]]
name = "lang#clojure"

[[layers]]
name = "lang#go"

[[layers]]
name = "lang#html"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#rust"

[[layers]]
name = "lang#sh"

[[layers]]
name = "lang#toml"

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#janet"
