[options]
  autocomplete_method = "deoplete"
  auto_disable_touchpad = 1
  automatic_update = false # Updating manually: git -C ~/.SpaceVim pull
  bootstrap_after = "myspacevim#after"
  bootstrap_before = "myspacevim#before"
  buffer_index_type = 4
  colorscheme = "nord"
  colorscheme_bg = "dark"
  disabled_plugins = ['markdown-preview.nvim', 'vim-import-js']
  enable_ale = true
  enable_filetree_gitstatus = true
  enable_guicolors = true
  enable_language_specific_leader = false
  enable_neomake = false
  enable_statusline_mode = false
  enable_tabline_filetype_icon = true
  enable_vimfiler_gitstatus = true
  filemanager = "nerdtree"
  filetree_direction = "left"
  hosts_url = "https://gist.githubusercontent.com/loganlinn/81e8448cc8c244c796e0e5ce16ab07a7/raw/4a7081fa5978f1e3285ae9c036b33aa86200fde2/hosts"
  lint_on_the_fly = true
  project_auto_root = 1
  project_rooter_outermost = 0
  project_rooter_patterns = [ '.SpaceVim.d/', '.bzr/', '.git/', '.hg/', '.svn/', 'Cargo.toml', '_darcs/', 'deps.edn', 'package.json', 'project.clj', ]
  projects_cache_num = 100
  src_root = "~/src"
  statusline_iseparator = "bar"
  statusline_separator = "arrow"
  statusline_unicode_symbols = true
  vimcompatible = true
  windows_index_type = 3

#######################################
## language server

[[plugins]]
  repo = 'autozimu/LanguageClient-neovim'
  branch = 'next'
  hook_post_update = "call system('bash install.sh')"

#######################################
## colors + visual

[[custom_plugins]]
  repo = "arcticicestudio/nord-vim"
  merged = false

#######################################
## runtime + syntax 

[[custom_plugins]]
  repo = "fladson/vim-kitty"
  merged = false

[[custom_plugins]]
  repo = "vito-c/jq.vim"
  merged = false

[[custom_plugins]]
  repo = "z0mbix/vim-shfmt"
  merged = false

[[custom_plugins]]
  repo = "axvr/org.vim"
  merged = false

[[custom_plugins]]
  repo = "mboughaba/i3config.vim"
  merged = false

#######################################
## utils

[[custom_plugins]]
  repo = "tpope/vim-dispatch"
  merged = false

[[custom_plugins]]
  repo = "radenling/vim-dispatch-neovim"
  merged = false
  if = "has('nvim')"

[[custom_plugins]]
  repo = "tpope/vim-eunuch"
  merged = false

[[custom_plugins]]
  repo = "tpope/vim-characterize"
  merged = false

[[custom_plugins]]
  repo = "junegunn/fzf.vim"
  merged = false

[[custom_plugins]]
  repo = "guns/xterm-color-table.vim"
  merged = false

#######################################
## clojure

[[custom_plugins]]
  repo = "tpope/vim-sexp-mappings-for-regular-people"
  merged = false

[[custom_plugins]]
  repo = "guns/vim-sexp"
  merged = false

[[custom_plugins]]
  repo = "clojure-vim/vim-jack-in"
  merged = false

[[custom_plugins]]
  repo = "Olical/conjure"
  merged = false

#[[custom_plugins]]
#  repo = "clojure-vim/acid.nvim"
#  merged = false
#
#[[custom_plugins]]
#  repo = "clojure-vim/jazz.nvim"
#  merged = false

[[custom_plugins]]
  repo = "clojure-vim/async-clj-omni"
  merged = false

#######################################

[[custom_plugins]]
  repo = "hashivim/vim-terraform"
  merged = false

#######################################
## apps

[[custom_plugins]]
  repo = "itchyny/calendar.vim"
  merged = false

[[custom_plugins]]
  repo = "soywod/himalaya"
  rtp = "email-manager/vim"
  merged = false
  on_cmd = "Himalaya"

#######################################
## layers

[[layers]]
  name = 'autocomplete'
  # auto_completion_return_key_behavior = "complete"
  # auto_completion_tab_key_behavior = "smart"
  auto_completion_enable_snippets_in_popup = true

[[layers]]
  name = "checkers"

[[layers]]
  name = "ctrlspace"

# [[layers]]
#   name = "debug"

# [[layers]]
#   name = "edit"

[[layers]]
  name = "format"

[[layers]]
  name = "fuzzy"

[[layers]]
  name = "fzf"

[[layers]]
  name = "git"

[[layers]]
  name = 'github'

[[layers]]
  name = "lsp"

# [[layers]]
#   name = "mail"

[[layers]]
  name = "org"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "sudo"

[[layers]]
  name = "tmux"

[[layers]]
  name = "tools"

[[layers]]
	name = "VersionControl"
	enable-gtm-status = true

#######################################
## langs

# [[layers]]
#   name = "lang#asciidoc"
#
# [[layers]]
#   name = "lang#c"

[[layers]]
  name = "lang#clojure"

[[layers]]
  name = "lang#dockerfile"

# [[layers]]
#   name = "lang#elixir"

[[layers]]
  name = "lang#elm"

# [[layers]]
#   name = "lang#erlang"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#graphql"

[[layers]]
  name = "lang#html"

# [[layers]]
#   name = "lang#ipynb"

# [[layers]]
#   name = "lang#janet"

[[layers]]
  name = "lang#java"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#json"

# [[layers]]
  # name = "lang#kotlin"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#nix"

# [[layers]]
#   name = "lang#plantuml"

[[layers]]
  name = "lang#python"

# [[layers]]
#   name = "lang#r"

# [[layers]]
#   name = "lang#ruby"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#toml"

# [[layers]]
#   name = "lang#typescript"

# [[layers]]
#   name = "lang#vim"

# [[layers]]
#   name = "lang#wolfram"

[[layers]]
  name = 'lang#xml'

# [[layers]]
#   name = 'lang#zig'
