[options]
  auto_disable_touchpad = 1
  automatic_update = false
  bootstrap_before = "myspacevim#before"
  bootstrap_after = "myspacevim#after"
  buffer_index_type = 4
  colorscheme = "nord"
  colorscheme_bg = "dark"
  # disabled_plugins = []
  enable_guicolors = true
  enable_neomake = true
  enable_statusline_mode = false
  enable_tabline_filetype_icon = true
  enable_vimfiler_gitstatus = true
  filemanager = "nerdtree"
  filetree_direction = "left"
  #guifont = "JetBrainsMono Nerd Font Mono:h11"
  hosts_url = "https://gist.githubusercontent.com/loganlinn/81e8448cc8c244c796e0e5ce16ab07a7/raw/4a7081fa5978f1e3285ae9c036b33aa86200fde2/hosts"
  statusline_iseparator = "bar"
  statusline_separator = "arrow"
  statusline_unicode_symbols = true
  vimcompatible = true
  windows_index_type = 3

[[plugins]]
  repo = 'autozimu/LanguageClient-neovim'
  hook_post_update = "call system('bash install.sh')"

[[custom_plugins]]
  repo = "arcticicestudio/nord-vim"
  merged = false

[[custom_plugins]]
  repo = "fladson/vim-kitty"
  merged = false

[[custom_plugins]]
  repo = "vito-c/jq.vim"
  merged = false

[[custom_plugins]]
  repo = "jparise/vim-graphql"
  merged = false

[[custom_plugins]]
  repo = "z0mbix/vim-shfmt"
  merged = false

[[custom_plugins]]
  repo = "guns/vim-sexp"
  merged = false

[[custom_plugins]]
  repo = "tpope/vim-sexp-mappings-for-regular-people"
  merged = false

# [[custom_plugins]]
#   repo = "Olical/conjure"
#   merged = false

[[custom_plugins]]
  repo = "hashivim/vim-terraform"
  merged = false

[[custom_plugins]]
  repo = "itchyny/calendar.vim"
  merged = false

[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = "checkers"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "tmux"

[[layers]]
  name = "fzf"

[[layers]]
  name = "git"

[[layers]]
  name = "shell"
  default_position = "float"

[[layers]]
  name = "lang#clojure"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#html"

[[layers]]
  name = 'lang#xml'

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#toml"

# [[layers]]
#   name = "lang#typescript"

# [[layers]]
#   name = "lang#janet"

[[layers]]
  name = "lang#nix"
