show_hidden           last
sort_by_last_modified last
respect_ignores       last
show_preview          last

map alt+enter         modifyname
map ctrl+0            next first_on_screen
map ctrl+1            cd ~/src/github.com/gamma-app
map ctrl+2            cd ~/src/github.com/loganlinn
map ctrl+3            cd ~/Downloads
map ctrl+4            cd ~/.config
map ctrl+5            cd ~/.local
map ctrl+5            cd ~/Notes
map ctrl+6            cd ~/Documents
map ctrl+7            cd ~/Pictures
map ctrl+8            cd ~/Music
map ctrl+9            cd ~/Dropbox
map ctrl+backspace    cd ..
map ctrl+c            quit
map ctrl+enter        typename
map ctrl+g            quit
map ctrl+h            next left
map ctrl+j            next 1
map ctrl+k            next -1
map ctrl+l            next right
map ctrl+n            next 1
map ctrl+p            next -1
map ctrl+x            select
map ctrl+space        toggle preview
map enter             accept
map esc               quit
map shift+enter       select
map shift+tab         cd ..
map tab               cd .
map home              next first_on_screen
map ctrl+home         next first
map down              next 1
map up                next -1
map left              next left
map right             next right
map end               next last_on_screen
map ctrl+end          next last
map ctrl+/            cd /
map ctrl+~            cd ~
map ctrl+`            cd ~
map ctrl+shift+`      cd ~
map ctrl+t            cd /tmp
map ctrl+]            1
map ctrl+[            -1
map ctrl+.            toggle dotfiles
map ctrl+i            toggle ignorefiles
map ctrl+d            toggle sort_by_dates
