hostname *.internal
color_scheme kanagawabones
share_connections no # breaks ssh agent forwarding
forward_remote_control no # requires share_connections

hostname fire.walla
color_scheme Gruvbox Light Soft
