hostname *
askpass ssh
delegate ssh
share_connections no # breaks ssh agent forwarding
forward_remote_control no # requires share_connections

hostname nijusan nijusan.internal
color_scheme kanagawabones
share_connections yes
forward_remote_control yes

hostname fire.walla
color_scheme Gruvbox Light Soft
