# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager: !!null delta -s
# Aliases allow you to create nicknames for gh commands
aliases:
    aliases: alias list
    config: '!${EDITOR:-editor} ~/.config/gh/config.yml'
    open: repo view --web
    co: pr checkout
    pro: pr view --web
    pro: pr view --web
    prm: pr merge --rebase --delete-branch
    prs: >-
        pr list --json number,title,headRefName --template '{{range .}}{{tablerow (printf "#%v" .number | autocolor "green") (.title | autocolor "white+h") (.headRefName | autocolor "blue")}}{{end}}'
    pr1: >-
        !gh prs | fzf --ansi --color  | awk '{print $1}'
    land: >-
        !pr="$(gh prs | fzf | awk '{print $1}')" && [ -n "$pr" ] && gh pr merge --rebase --delete-branch "$pr"
    landf: >-
        !pr="$(gh prs | fzf | awk '{print $1}')" && [ -n "$pr" ] && gh pr merge --rebase --delete-branch --admin "$pr" "$@"
    # Fuzzy-find a gist with fzf, then view it
    gists: "!GIST=$(gh gist list --limit 128 | fzf -0 | cut -f1) || exit $? ; [[ -n $GIST ]] && gh gist view \"$GIST\" $@"
