# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager: !!null delta -s
# Aliases allow you to create nicknames for gh commands
aliases:
    aliases: alias list

    edit-config: '!${EDITOR:-editor} ~/.config/gh/config.yml'
    aliases-edit: '!${EDITOR:-editor} ~/.config/gh/config.yml'

    # Fuzzy-find a gist with fzf, then view it
    gists: >-
        !GIST=$(gh gist list --limit 128 | fzf -0 | cut -f1) || exit $? ; [[ -n $GIST ]] && gh gist view \"$GIST\" $@"

    stars: >-
        api user/starred --template '{{range .}}{{tablerow .full_name .description .html_url }}{{end}}'

    open: browse
    open-prs: pr list --web
    open-pr: pr view --web
    open-issues: issue list --web
    open-release: release view --web
    prs-open: pr list --web
    pr-open: pr view --web
    issue-opens: issue list --web
    release-open: release view --web

    prs: pr list --web

    prl: >-
      pr list
        --json number,title,headRefName
        --template '{{range .}}{{tablerow (printf "#%v" .number | autocolor "green") (.title | autocolor "white+h") (.headRefName | autocolor "blue")}}{{end}}'
      
    # Interactively select one PR
    pr1: >-
      !gh prl "$@" | fzf --ansi --color  | awk '{print $1}'

    # Interactively checkout a PR
    prco: >-
        !gh pr1 | ifne xargs -n1 gh pr checkout

    # Interactively merge my PR
    land: >-
        !gh pr1 --author=@me | ifne xargs -n1 gh pr merge --rebase --delete-branch
    landf: >-
        !gh pr1 --author=@me | ifne xargs -n1 gh pr merge --rebase --delete-branch --admin
