[
  ../../nix/home/common.nix
  ../../nix/home/dev
  ../../nix/home/dunst
  ../../nix/home/emacs
  ../../nix/home/eww
  ../../nix/home/home-manager.nix
  ../../nix/home/intellij.nix
  ../../nix/home/kitty
  ../../nix/home/mpd.nix
  ../../nix/home/mpv.nix
  ../../nix/home/nnn.nix
  ../../nix/home/polkit.nix
  ../../nix/home/pretty.nix
  ../../nix/home/qalculate
  ../../nix/home/sync.nix
  ../../nix/home/urxvt.nix
  ../../nix/home/vpn.nix
  ../../nix/home/vscode.nix
  ../../nix/home/x11.nix
  ../../nix/home/yt-dlp.nix
  ../../nix/home/yubikey.nix
  ../../nix/modules/programs/the-way
  ../../nix/modules/services
  ../../nix/modules/spellcheck.nix
  ../../nix/modules/desktop
  ../../nix/modules/desktop/browsers
  ../../nix/modules/desktop/browsers/firefox.nix
  ../../nix/modules/desktop/i3
]
