#!/usr/bin/env zsh

antigen bundles <<EOBUNDLES
  colored-man-pages
  fzf
  git
  gitignore
  gpg-agent
  ssh-agent
  urltools
  zsh-interactive-cd
EOBUNDLES

antigen bundles <<EOBUNDLES
  hlissner/zsh-autopair
  kazhala/dotbare
  loganlinn/zzz.plugin.zsh
  wfxr/forgit
  zsh-users/zsh-history-substring-search
  zsh-users/zsh-autosuggestions
  zsh-users/zsh-syntax-highlighting
  zsh-users/zsh-completions
EOBUNDLES

for _zsh_custom_plugin in $ZSH_CUSTOM/plugins/*(/); do
  antigen bundle "$_zsh_custom_plugin" --no-local-clone
done
unset _zsh_custom_plugin

# zsh-users/zsh-autosuggestions
export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
export ZSH_AUTOSUGGEST_USE_ASYNC=1

# wfxr/forgit
export FORGIT_NO_ALIASES=1
export FORGIT_FZF_DEFAULT_OPTS='--preview-window=right:80%'
export FORGIT_ADD_FZF_OPTS='--ansi'

alias glo=forgit::log
alias ga=forgit::add
alias gi=forgit::ignore
alias gcf=forgit::checkout::file
alias gcb=forgit::checkout::branch
alias gbd=forgit::branch::delete
alias gct=forgit::checkout::tag
alias gco=forgit::checkout::commit
alias grc=forgit::revert::commit
alias gclean=forgit::clean
alias gss=forgit::stash::show
alias gpick=forgit::cherry::pick
alias grb=forgit::rebase
alias gbl=forgit::blame
alias gfu=forgit::fixup

# kazhala/dotbare
export DOTBARE_DIR=$HOME/.dotfiles/.git
export DOTBARE_TREE=$HOME/.dotfiles

antigen apply
