#!/usr/bin/env zsh

antigen bundles <<EOBUNDLES
  colored-man-pages
  fzf
  git
  gitignore
  gpg-agent
  ssh-agent
  urltools
  zsh-interactive-cd
EOBUNDLES

antigen bundles <<EOBUNDLES
  hlissner/zsh-autopair
  loganlinn/zzz.plugin.zsh
  wfxr/forgit
  zsh-users/zsh-history-substring-search
  zsh-users/zsh-autosuggestions
  zsh-users/zsh-syntax-highlighting
  zsh-users/zsh-completions
EOBUNDLES

for _zsh_custom_plugin in $ZSH_CUSTOM/plugins/*(/); do
  antigen bundle "$_zsh_custom_plugin" --no-local-clone
done
unset _zsh_custom_plugin

# zsh-users/zsh-autosuggestions
export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
export ZSH_AUTOSUGGEST_USE_ASYNC=1

# wfxr/forgit
export FORGIT_FZF_DEFAULT_OPTS='--preview-window=right:80%'
export FORGIT_ADD_FZF_OPTS='--ansi'

antigen apply
