flake := env("FLAKE_ROOT", parent_dir(parent_dir(source_dir())))

# Builds nix derivation
[group('nix')]
[no-cd]
[positional-arguments]
build package *args:
    nix build \
      --impure \
      --print-build-logs \
      --json \
      --arg package "{{ absolute_path(source_dir() / package) }}" \
      --expr '{ package }: let pkgs = import (builtins.getFlake "{{ flake }}").inputs.nixpkgs {}; in pkgs.callPackage package {}' \
      "${@:2}"
