#!/usr/bin/env bash
#
# Prints nix expression for map of current keymap table
#

SCRIPT_GIT_PATH=$(
    cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &&
        printf %s "$(git rev-parse --show-prefix)" "$(basename "$0")"
) || exit

echo "# Code generated by $SCRIPT_GIT_PATH. DO NOT EDIT."
echo "{"
echo "  keysym = {"

xmodmap -pke |
    awk '
($1 == "keycode") {
  for (i=4; i<=NF; i++) {
    if ($i == "NoSymbol") continue
    print (length($i) == 1 ? 1 : 2) "\t" "    \"" $i "\" = \"" $i "\";"
  }
}' |
    sort -n -t$'\t' -k1,1 |
    uniq |
    cut -f1 --complement

echo "  };"
echo "}"
