#!/usr/bin/env bash

set -e
set -o pipefail

[[ -d ~/src/github.com/hlissner/doom-emacs ]] ||
  git clone --depth 1 https://github.com/hlissner/doom-emacs.git ~/src/github.com/hlissner/doom-emacs

[[ -e ~/.emacs.d ]] ||
  ln -sb ~/src/github.com/hlissner/doom-emacs ~/.emacs.d
