#!/usr/bin/env bash

FZF_BASE=$HOME/.fzf

if ! [[ -d $FZF_BASE ]]; then
	git clone --depth 1 https://github.com/junegunn/fzf.git "$FZF_BASE"
fi

if ! [[ -d ${XDG_CONFIG_HOME:-$HOME/.config}/fzf ]]; then
	"$FZF_BASE"/install --xdg --no-update-rc
fi
