plugin:
  stern:
    shortCut: Ctrl-L
    confirm: false
    description: "Logs <Stern>"
    scopes:
      - pods
      - jobs
      - daemonsets
      - statefulsets
    command: stern
    background: false
    args:
      - --tail
      - 50
      - $FILTER
      - -n
      - $NAMESPACE
      - --context
      - $CONTEXT
      - --exclude
      - "io.opentelemetry.exporter.logging.LoggingMetricExporter"

  lnav:
    shortCut: Ctrl-V
    confirm: false
    description: "Logs <lnav>"
    scopes:
      - pods
      - jobs
      - daemonsets
      - statefulsets
    command: kubectl-lnav
    background: false
    args:
      - --tail
      - 50
      - $FILTER
      - -n
      - $NAMESPACE
      - --context
      - $CONTEXT
  watch-events:
    shortCut: Shift-E
    confirm: false
    description: Get Events
    scopes:
    - all
    command: sh
    background: false
    args:
    - -c
    - "watch -n 5 kubectl get events --context $CONTEXT --namespace $NAMESPACE --field-selector involvedObject.name=$NAME"
