k9s:
  views:
    v1/namespaces:
      columns:
        - NAME
        - STATUS
        - AGE

    # v1/pods:
    #   columns:
    #     - AGE
    #     - NAMESPACE
    #     - NAME
    #     - IP
    #     - NODE
    #     - STATUS
    #     - READY

    # # Alters the service view column layout
    # v1/services:
    #   columns:
    #     - AGE
    #     - NAMESPACE
    #     - NAME
    #     - TYPE
    #     - CLUSTER-IP
