[settings]
experimental = true

[tools]
oxfmt = "latest"
watchexec = "latest"
pinact = "latest"
java = "21"
kafkactl = "latest"
terraform-docs = "latest"
hcl2json = "latest"
"go:github.com/hashicorp/hcl/v2/cmd/hcldec" = "latest"
"cargo:presenterm" = "latest"
fnox = "latest"
pkl = "latest"
bun = "latest"
"github:JamesWoolfenden/pike" = "latest"
process-compose = "latest"
"github:pamburus/hl" = "latest"
aws-nuke = "latest"
"go:github.com/ugosan/logshark/cmd" = "latest"
coder = "latest"
"go:go.k6.io/xk6/cmd/xk6" = "latest"
"github:corneliusweig/ketall" = "latest"
"github:robscott/kube-capacity" = "latest"
"github:launchdarkly/ldcli" = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }

[env]
DEVIN_API_KEY = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFaWGRsUSBrc3RRS0doRjRGRms3ckFOcjNML3hxNmNSUTdNbW96M3RBS2gxelEyMFNzCk5YbVpzaVNpNHJTS3F4dEwrNlhuMGlkOFNhaTdHMFhmSzgycnFjeksybm8KLT4gV1w9by1ncmVhc2UKZUJyNXV0UnVQSjBTQURnQk1tdnFJamh3eWJ4VHV3WVY1UDc3Rlo3aFMrYjhSQk05TTI3MGdrclViaVZHM1c3NQpTeWlSV21qZm1aNXlFQjh0V0ttd0hudWRQTzVLVm5sVFNEVDJtL3RJN3cKLS0tIENPRGxmM3kvTVRPMnpkS21zYjM5L2E1aGx0Y1ZrQ1ZzVW8vZU9sTnFVeHcKcMiqW88FZyU6f+RgksjQhjNKfp2RKP5NKq3CWQ4GDN0XUHHwRsaeOCMIrRPgagA1Vc2zfCr3Py4RvfTBrv6wRt17GsDVUEbItY5NvEQPZnbCIM61zmtjUg" }
DD_API_KEY = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFaWGRsUSAvRE9vZkZnRlVTZmtpVkJCRE13Q0dTaG1Ha0owMG5qbFZBK3N2YW1pSnd3CmFQTnRvMnVialhiVXU5dXNTdEU3ODR3cEZxWjczU2NqSkNoZk5adHBsSjQKLT4gZStKSUlcLWdyZWFzZSBrRmhTIDc4KEFyXTEKUWIxRkdmMGR5NjBVNnVSNUZnNWZFUXoxZVRrRU9zaitYdUhpR0hFYmEzZnNQRVFzYlNQcFpuMXEybGRmV0VxaApwKys3d1g2dk9HSmhiRjdtMVFCL3JaZWtyc25iWldEdzZaRGhKakk4bUhKMDR3bXc4MVdHbU1Fdyt1MAotLS0gWHZrcnd0V2ZuLzM0YUNaNG5TL3daSm9WMG80dkt6L0l2YXN0eXIwVkdPWQqdqgN3oIwmXbGbD882NgAudAGUNX85lKAzEv9sZJMJ1ZVHH6H7kpnqlQRkWgdVwGIl6UaZJrvv1dqP/gHIYTNL" }
# DD_APP_KEY = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFaWGRsUSBjSnd6OGcySXc5OFp3VStQOUovNjhEVkkyN2pydmI4Z3J4T0laSDRwT3dFCkNnTjVndmJBRnhqdko2YVhjeHNXWWJYekdVRnV1VFpPTWQ1OW1RTHBRSXcKLT4gej5zWS1ncmVhc2UgM3VRbWRfCkE4WWxXQWFRVkVuRzdTWWUKLS0tIENBNkYwYWw5Yjhwc2pNeGR0QlpmREZ0cnl6aU8vMndBL3Jmc2p6MElqWWsKiiGGEuYcZCXZsmiuaxlt1I5DhgjDvgC+oV10TocohnstV0/h3JnjugQ7S84DAA+RYxkkwg7iCgvOukDuzngsDpGLIvnwuWTP" }
# DD_API_KEY = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFaWGRsUSBlWnFWOWUyaS9KV3JHYWNoK0k3RWEyZmlCTHJ1MFRiazFIMVRPZUcweUV3ClhMZlhsa0Z1VlNORzFGNXE2TkVaQ2R2cEcxTmgzM0RtT1MxWDN4T2tXbFkKLT4gWS1ncmVhc2UgIms+UVEKalVacU5HbE05TUZpcFEKLS0tIE1wZkkvcFJJQktJaEJob2pyQXZYQSt3NFI1bG1QeGNmYkF0eWdlQ0k0YkkKQ14ci7MUTRK9IVlLkIkMMaK0CdRaIFyEKk9IZAQ5ntlr9UPdsNw2ROBj2050+I13k4iLiXbMUmLIsAwbC2lW7w" }
