[settings]
experimental = true

[tools]
oxfmt = "latest"
watchexec = "latest"
pinact = "latest"
java = "21"
kafkactl = "latest"
terraform-docs = "latest"
hcl2json = "latest"
"go:github.com/hashicorp/hcl/v2/cmd/hcldec" = "latest"
"cargo:presenterm" = "latest"
fnox = "latest"
pkl = "latest"
bun = "latest"
"github:JamesWoolfenden/pike" = "latest"
process-compose = "latest"
"github:pamburus/hl" = "latest"
aws-nuke = "latest"
"go:github.com/ugosan/logshark/cmd" = "latest"
coder = "latest"
"go:go.k6.io/xk6/cmd/xk6" = "latest"
"github:corneliusweig/ketall" = "latest"
"github:robscott/kube-capacity" = "latest"
"github:launchdarkly/ldcli" = "latest"

# [tasks."s3:pull"]
# usage = '''
# arg "[options]" var=#true
# arg "<s3_path>"
# '''
# run = ['''aws s3 sync s3://'{{ usage.s3_path }}' ~/s3/'{{ usage.s3_path }}'''']

# [tasks."s3:pull:terraform"]
# run = [
#   '''aws s3 sync s3://gamma-terraform ~/s3/gamma-terraform''',
#   '''fd .tfstate ~/s3/gamma-terraform -X chmod 600''',
# ]
