github_token: ENC[AES256_GCM,data:dYwgTkMR5zR5DjFNcRI7CJK48RHFAlnqZCTX4XmDYBxIjUlOHtYbaQ==,iv:Tsm91nhsg/2fMIrGEX6Vl+HfkdMj0UdHt3LCybZHu5k=,tag:YylMpFJfzoucUYpUKtLadg==,type:str]
sops:
    shamir_threshold: 1
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15xagf0337s3w73sps8dfpnup39rglkul8km9hkc8m9daz5yldu4qqr4yfl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZFlrTjBQRUhxNzF2RnRp
            K2lxN0lUM1pTaXFsTklmSklYcld3a0JzTXhFClNTMXQ5Mms4Z3dGUnZWbFRFY2pF
            L0JTLzA4bHQ4eVdRdDROVFhiYVlOK28KLS0tIFRaRWdvOERYeVBTYmViM3lvc25j
            emtGVmNuS2hqbFgyQXpqYWlSakhVTWcKZ0Zj8nRvV1SQVgJF1NsGSfG9C4m4yc8A
            uPDuPkoWkhjdsykNIfNxDuJCrkliZi1xxlSfrCQde3a1I2cjtL7cog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-22T07:01:26Z"
    mac: ENC[AES256_GCM,data:lv9ELicZV9j83/LQZuvYKF96v+Gp0+XDREKR7Ypns05ghGZZBuFqgRs9GDX560arHcm8O3DBcmY7A3+/zQKQoxeGB5EmVqr5c9uA7QYjclRPLKSsWvQm8AnXuB+USriWlD9hAprBNGVKHt0jh5SLwbYzuuUIKAqh3ccI3PxzSWI=,iv:44AIO/1I/+kseGOE0AduE9cs1TEiy7yg/b7IrJ2jRGQ=,tag:tCMRP65eUOhiMKqQnJBgcA==,type:str]
    pgp:
        - created_at: "2023-03-05T09:19:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcDMA47NG3R7IBFJAQv/egM/FcJAv+/w+S43aieXxikZomajd5CXS2AqiHMc41Ta
            TpAicS2Yc135yPLMqyapv2YNzZNFTR+O25N/MaFg7yE2dXWxmobwxyW0VvzDW9Fm
            RQ6BocX9Bc8yeRyXefpTsgXi2uwAdUZfe7X1klVKQv722V2s72zeCwPlq/E6Mumc
            GyCtn0q5t/100CO3dMrIWRcxCe+6Jlygiy+ECIJysA8yCWiJxwD6rLMso120vflj
            RtMJiH81zjkQdVSaexo968PrXpqvKsv+XZfBfQplQEHcA8VMThUK9PxrqgB1YuoI
            zE0srq586Ga0nsgv6kHQu6LU+rGD+z1ODEDiDf5GbftI0fsf9uRB1hu9CSDKU0bq
            4CaiAoJ6g/MQvZgtdHj7CfbdFo0dk3c46FzKJNJWKyr5BQGhqhpZ+SH1KloKmMwP
            RxcPice8RJlBdwppx9lO6EJIKepele2C0FyTvso9t4DeAxlAWcLMztjL4lcNdq1O
            Z1jP+BptILDwpRun4Pn/0lEBjVhbtPncuhQYLTXo+WQXK23sGbV5zgLLciCOW1I3
            SIWVLhocAFv0da+Kpq9px9LvASGdT4NCa0UXXdfNh9cdiIZ4DM3kHW2ir5r9nClA
            NzA=
            =Pq6A
            -----END PGP MESSAGE-----
          fp: 32A48B412F1CA30ADB1B54382C3CDAE023DB6616
    unencrypted_suffix: _unencrypted
    version: 3.7.3
