github_token: ENC[AES256_GCM,data:dYwgTkMR5zR5DjFNcRI7CJK48RHFAlnqZCTX4XmDYBxIjUlOHtYbaQ==,iv:Tsm91nhsg/2fMIrGEX6Vl+HfkdMj0UdHt3LCybZHu5k=,tag:YylMpFJfzoucUYpUKtLadg==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - pgp:
            - created_at: "2023-02-22T06:35:40Z"
              enc: |-
                -----BEGIN PGP MESSAGE-----

                wcDMA47NG3R7IBFJAQv+IYawqlfA3CEYJeu63l07SRGWQE9uFDJR0A1qJOZ0hcL/
                bMQ9VUAuD2q7H9L3TKBd7V2S/PnBylRIId/vFUWwRpeNgF76UAwPs13CPtqCFlEu
                BHsS9p859jZOh+Dwu8ESZpQr7lzN7lecp2/kDd4mGrX5zd3IPvF65vW1I0euTkBj
                qQegO3Z1D/gGp76y4aFjj1DB5bzXMm+GtF1gDCZxYr/b+GC5APZa2+5mNRQ/4RAc
                HBV0e69xIuUpJyDD4mYH2cdThZnPxdRroE2pKWLVZubomK52O45IzWmVV+hVHfSO
                R7/1QdnzdhGWoGFelBZq06SxnVThDQMEh4sMMM/NyEvDTmXr27CBmJWuAHj803Qn
                6XmLZOabtwoY778+B1MMDXR0j+qG1G7OAumRokte2ST9Bx+a0iXJkmgKJMP1KBkN
                YkWn09F8FNAQCkQct6ldYsZycen+UAR+PzJ8rQLBaiJz9crxZNl9kxdXkzfDVd6X
                GaE6yDj4cUANiaB/ktVb0lIBJgmeiWO/DyExBS9g1uIbYgVXM0e/KiUl3okRf8QD
                WQt2ehjmbJu6W1H7hgnMaI5ea9aP6eUSf8dZ1p3Gv9qYeVdCDE90AQP9IDFvW22q
                H7Z0
                =qWze
                -----END PGP MESSAGE-----
              fp: 32A48B412F1CA30ADB1B54382C3CDAE023DB6616
          hc_vault: []
          age: []
        - hc_vault: []
          age:
            - recipient: age1nrxg0qkcqfx5s76x3md2jakwd9tslqry0y2k0lp4u4ngjje4z3dq8v3xyq
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdW1vVjJxejZOVDB2S1gr
                WmxRbHV5NHJycnhlQWtTcUV1N3dVb0tXNnpvCkRUSWd6MXdPQ1FXVm9pM2tBWHlD
                QlV5UWtaZ05VWGNFbE9XeFFXRXVmQzgKLS0tIEpXYjFaSVJlczF0SmcyejBKMWNU
                eXQxYjVLbk1helQ1VFFZWEhLWkVycmsKu3aLePuOwypyzDJ8k9bf/vn1TefoPUjv
                ICEJr7opEPZO104s7ZGvvZ2N4fnPtT5HIXoPCdm12aROElBZ6U4cz6g=
                -----END AGE ENCRYPTED FILE-----
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-22T07:01:26Z"
    mac: ENC[AES256_GCM,data:lv9ELicZV9j83/LQZuvYKF96v+Gp0+XDREKR7Ypns05ghGZZBuFqgRs9GDX560arHcm8O3DBcmY7A3+/zQKQoxeGB5EmVqr5c9uA7QYjclRPLKSsWvQm8AnXuB+USriWlD9hAprBNGVKHt0jh5SLwbYzuuUIKAqh3ccI3PxzSWI=,iv:44AIO/1I/+kseGOE0AduE9cs1TEiy7yg/b7IrJ2jRGQ=,tag:tCMRP65eUOhiMKqQnJBgcA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
